'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '../../lib/supabase/client';

type Task={id:string;name:string;category:string;due_date:string;repeat_days:number;completed_at:string|null};
const day=(n:number)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
const starter:Task[]=[{id:'demo1',name:'Replace HVAC filter',category:'HVAC',due_date:day(4),repeat_days:90,completed_at:null},{id:'demo2',name:'Test smoke & CO detectors',category:'Safety',due_date:day(12),repeat_days:180,completed_at:null},{id:'demo3',name:'Clean dryer vent',category:'Appliances',due_date:day(-6),repeat_days:365,completed_at:null},{id:'demo4',name:'Inspect gutters',category:'Exterior',due_date:day(28),repeat_days:180,completed_at:null}];
const icons:Record<string,string>={HVAC:'❄️',Safety:'🛡️',Plumbing:'💧',Appliances:'⚙️',Exterior:'🏡',Cleaning:'✨',Other:'🔧'};

export default function Dashboard(){
 const[tasks,setTasks]=useState<Task[]>(starter),[userId,setUserId]=useState<string|null>(null),[name,setName]=useState(''),[category,setCategory]=useState('HVAC'),[due,setDue]=useState(day(7)),[repeat,setRepeat]=useState(90),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{try{const s=createBrowserSupabase();const{data:{user}}=await s.auth.getUser();if(!user)return;setUserId(user.id);const{data,error}=await s.from('maintenance_tasks').select('id,name,category,due_date,repeat_days,completed_at').order('due_date');if(error)throw error;if(data)setTasks(data)}catch{}})()},[]);
 const counts=useMemo(()=>{const now=new Date().toISOString().slice(0,10);let overdue=0,soon=0,done=0;for(const t of tasks){if(t.completed_at)done++;else if(t.due_date<now)overdue++;else if((new Date(t.due_date).getTime()-Date.now())/86400000<=30)soon++}return{overdue,soon,done}},[tasks]);
 const score=Math.max(55,Math.min(100,100-counts.overdue*12-counts.soon*2+counts.done*2));
 async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;const temp={id:crypto.randomUUID(),name:name.trim(),category,due_date:due,repeat_days:repeat,completed_at:null};if(!userId){setTasks(x=>[...x,temp]);setName('');setMsg('Demo mode: sign in to save reminders permanently.');return}try{const s=createBrowserSupabase();const{data,error}=await s.from('maintenance_tasks').insert({user_id:userId,name:temp.name,category,due_date:due,repeat_days:repeat}).select('id,name,category,due_date,repeat_days,completed_at').single();if(error)throw error;setTasks(x=>[...x,data]);setName('');setMsg('Reminder saved.')}catch(err){setMsg(err instanceof Error?err.message:'Could not save reminder.')}}
 async function complete(t:Task){const next=new Date(`${t.due_date}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+t.repeat_days);const nextDate=next.toISOString().slice(0,10);const completedAt=new Date().toISOString();if(!userId){setTasks(x=>x.map(i=>i.id===t.id?{...i,due_date:nextDate,completed_at:completedAt}:i));return}try{const s=createBrowserSupabase();const{error}=await s.from('maintenance_tasks').update({completed_at:completedAt,due_date:nextDate}).eq('id',t.id);if(error)throw error;setTasks(x=>x.map(i=>i.id===t.id?{...i,due_date:nextDate,completed_at:completedAt}:i))}catch(err){setMsg(err instanceof Error?err.message:'Could not update task.')}}
 function status(t:Task){const today=new Date().toISOString().slice(0,10);if(t.completed_at)return['done','Completed'];if(t.due_date<today)return['overdue','Overdue'];const d=Math.ceil((new Date(t.due_date).getTime()-Date.now())/86400000);if(d<=30)return['soon',d<=0?'Due today':`Due in ${d}d`];return['',`Due ${new Date(t.due_date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}`]}
 return <main className="shell">
  <header className="topbar"><div className="brandWrap"><div className="brandMark">⌂</div><div><div className="brand">HomeKeep</div><div className="muted" style={{fontSize:13}}>Your home at a glance</div></div></div><span className="badge">{userId?'● Synced':'Demo mode'}</span></header>

  <section className="dashboardHero">
    <div className="card scoreCard"><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:13,opacity:.8,fontWeight:700}}>HOME HEALTH</div><h1 style={{fontSize:34,margin:'8px 0 8px',letterSpacing:'-1px'}}>You’re keeping your home on track.</h1><div style={{opacity:.8,maxWidth:540,lineHeight:1.5}}>{counts.overdue?`You have ${counts.overdue} overdue ${counts.overdue===1?'task':'tasks'} to knock out.`:'No overdue maintenance right now. Nice work.'}</div></div><div className="scoreRing" style={{'--score':`${score}%`} as React.CSSProperties}><div className="scoreValue">{score}</div></div></div></div>
    <div className="card"><div className="sectionTitle">This month</div><p className="muted" style={{marginTop:4}}>A quick look at what needs attention.</p><div className="quickGrid"><div className="quickItem"><div className="stat">{counts.overdue}</div><div className="quickLabel">Overdue</div></div><div className="quickItem"><div className="stat">{counts.soon}</div><div className="quickLabel">Due soon</div></div><div className="quickItem"><div className="stat">{counts.done}</div><div className="quickLabel">Completed</div></div><div className="quickItem"><div className="stat">{tasks.length}</div><div className="quickLabel">Tracked</div></div></div></div>
  </section>

  <section id="add" className="card"><div className="sectionHead"><div><h2 className="sectionTitle">Add a maintenance reminder</h2><div className="muted">Tell HomeKeep what to remember.</div></div><span className="badge">+ New task</span></div><form onSubmit={add} className="formGrid"><label className="field">Task<input className="input" value={name} onChange={e=>setName(e.target.value)} required placeholder="Replace HVAC filter"/></label><label className="field">Category<select className="input" value={category} onChange={e=>setCategory(e.target.value)}>{Object.keys(icons).map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Next due<input className="input" type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><label className="field">Repeat<select className="input" value={repeat} onChange={e=>setRepeat(Number(e.target.value))}><option value={30}>Monthly</option><option value={90}>Every 3 months</option><option value={180}>Every 6 months</option><option value={365}>Yearly</option></select></label><button className="btn btnPrimary" type="submit">Save reminder</button></form>{msg&&<div className="message">{msg}</div>}</section>

  <section id="schedule" className="card" style={{marginTop:16}}><div className="sectionHead"><div><h2 className="sectionTitle">Maintenance schedule</h2><div className="muted">Your next home-care jobs, in order.</div></div><span className="badge">{tasks.length} tracked</span></div><div className="taskList">{tasks.length===0?<div className="empty">No maintenance reminders yet.</div>:tasks.slice().sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(t=>{const [cls,label]=status(t);return <div className="task" key={t.id}><div className="taskMain"><div className="taskIcon">{icons[t.category]||'🔧'}</div><div><div className="taskName">{t.name}</div><div className="taskMeta">{t.category} · repeats every {t.repeat_days} days</div><div style={{marginTop:8}}><span className={`statusPill ${cls}`}>{label}</span></div></div></div><button className="btn btnGhost btnSmall" onClick={()=>complete(t)}>✓ Mark done</button></div>})}</div></section>

  <nav className="bottomNav"><Link className="active" href="/dashboard"><span className="navIcon">⌂</span><span>Home</span></Link><a href="#add"><span className="navIcon">＋</span><span>Add</span></a><a href="#schedule"><span className="navIcon">☷</span><span>Schedule</span></a></nav>
 </main>
}
