'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createBrowserSupabase} from '../../lib/supabase/client';

type Task={id:string;name:string;category:string;due_date:string;repeat_days:number;last_completed_at:string|null};
type HistoryItem={id:string;task_id:string;completed_at:string};
type ReminderNotice={id:string;task_id:string|null;title:string;body:string;kind:string;created_at:string;read_at:string|null};
type ReminderSettings={enabled:boolean;days_before:number;remind_overdue:boolean;timezone:string};

const day=(n:number)=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
const starter:Task[]=[
 {id:'demo1',name:'Replace HVAC filter',category:'HVAC',due_date:day(4),repeat_days:90,last_completed_at:null},
 {id:'demo2',name:'Test smoke & CO detectors',category:'Safety',due_date:day(12),repeat_days:180,last_completed_at:null},
 {id:'demo3',name:'Clean dryer vent',category:'Appliances',due_date:day(-6),repeat_days:365,last_completed_at:null},
 {id:'demo4',name:'Inspect gutters',category:'Exterior',due_date:day(28),repeat_days:180,last_completed_at:null}
];
const icons:Record<string,string>={HVAC:'❄️',Safety:'🛡️',Plumbing:'💧',Appliances:'⚙️',Exterior:'🏡',Cleaning:'✨',Other:'🔧'};

export default function Dashboard(){
 const[tasks,setTasks]=useState<Task[]>(starter),[history,setHistory]=useState<HistoryItem[]>([]),[userId,setUserId]=useState<string|null>(null);
 const[name,setName]=useState(''),[category,setCategory]=useState('HVAC'),[due,setDue]=useState(day(7)),[repeat,setRepeat]=useState(90),[msg,setMsg]=useState('');
 const[notices,setNotices]=useState<ReminderNotice[]>([]),[showNotices,setShowNotices]=useState(false),[showHistory,setShowHistory]=useState(false);
 const[settings,setSettings]=useState<ReminderSettings>({enabled:true,days_before:3,remind_overdue:true,timezone:'America/New_York'}),[noticeMsg,setNoticeMsg]=useState('');

 useEffect(()=>{(async()=>{try{
  const s=createBrowserSupabase();const{data:{user}}=await s.auth.getUser();if(!user)return;setUserId(user.id);
  const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'America/New_York';
  const[{data:t,error},{data:h},{data:n},{data:pref}]=await Promise.all([
   s.from('maintenance_tasks').select('id,name,category,due_date,repeat_days,last_completed_at').order('due_date'),
   s.from('maintenance_history').select('id,task_id,completed_at').order('completed_at',{ascending:false}).limit(50),
   s.from('notifications').select('id,task_id,title,body,kind,created_at,read_at').order('created_at',{ascending:false}).limit(20),
   s.from('notification_settings').select('enabled,days_before,remind_overdue,timezone').eq('user_id',user.id).maybeSingle()
  ]);
  if(error)throw error;if(t)setTasks(t as Task[]);if(h)setHistory(h as HistoryItem[]);if(n)setNotices(n as ReminderNotice[]);
  const nextPref=pref?{enabled:pref.enabled,days_before:pref.days_before,remind_overdue:pref.remind_overdue,timezone:pref.timezone}:{enabled:true,days_before:3,remind_overdue:true,timezone:tz};
  setSettings(nextPref);await s.from('notification_settings').upsert({user_id:user.id,...nextPref,timezone:tz},{onConflict:'user_id'});
  if(n&&typeof window!=='undefined'&&'Notification'in window&&Notification.permission==='granted'){
   (n as ReminderNotice[]).filter(x=>!x.read_at).slice(0,3).forEach(x=>{const key=`homekeep-notice-${x.id}`;if(!sessionStorage.getItem(key)){new Notification(x.title,{body:x.body});sessionStorage.setItem(key,'1')}})
  }
 }catch{}})()},[]);

 const unread=notices.filter(x=>!x.read_at).length;
 const taskById=useMemo(()=>new Map(tasks.map(t=>[t.id,t])),[tasks]);
 const counts=useMemo(()=>{const today=new Date().toISOString().slice(0,10);let overdue=0,soon=0;for(const t of tasks){if(t.due_date<today)overdue++;else if((new Date(t.due_date).getTime()-Date.now())/86400000<=30)soon++}const monthAgo=Date.now()-30*86400000;const done=history.filter(h=>new Date(h.completed_at).getTime()>=monthAgo).length;return{overdue,soon,done}},[tasks,history]);
 const score=Math.max(55,Math.min(100,100-counts.overdue*12-counts.soon*2+counts.done*2));

 async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;const temp:Task={id:crypto.randomUUID(),name:name.trim(),category,due_date:due,repeat_days:repeat,last_completed_at:null};if(!userId){setTasks(x=>[...x,temp]);setName('');setMsg('Demo mode: sign in to save reminders permanently.');return}try{const s=createBrowserSupabase();const{data,error}=await s.from('maintenance_tasks').insert({user_id:userId,name:temp.name,category,due_date:due,repeat_days:repeat}).select('id,name,category,due_date,repeat_days,last_completed_at').single();if(error)throw error;setTasks(x=>[...x,data as Task]);setName('');setMsg('Reminder saved.')}catch(err){setMsg(err instanceof Error?err.message:'Could not save reminder.')}}

 async function complete(t:Task){if(!userId){const completed=new Date().toISOString(),next=day(t.repeat_days);setTasks(x=>x.map(i=>i.id===t.id?{...i,due_date:next,last_completed_at:completed}:i));setHistory(x=>[{id:crypto.randomUUID(),task_id:t.id,completed_at:completed},...x]);setMsg(`${t.name} completed. Next due date scheduled.`);return}try{const s=createBrowserSupabase();const{data,error}=await s.rpc('complete_maintenance_task',{p_task_id:t.id});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error('Completion did not return a next due date.');setTasks(x=>x.map(i=>i.id===t.id?{...i,due_date:row.next_due_date,last_completed_at:row.completed_on}:i));setHistory(x=>[{id:crypto.randomUUID(),task_id:t.id,completed_at:row.completed_on},...x]);setNotices(x=>x.map(n=>n.task_id===t.id&&!n.read_at?{...n,read_at:row.completed_on}:n));setMsg(`${t.name} completed. Next due ${new Date(row.next_due_date+'T00:00:00').toLocaleDateString()}.`)}catch(err){setMsg(err instanceof Error?err.message:'Could not complete task.')}}

 async function markRead(id:string){if(!userId)return;const s=createBrowserSupabase();const now=new Date().toISOString();await s.from('notifications').update({read_at:now}).eq('id',id);setNotices(x=>x.map(n=>n.id===id?{...n,read_at:now}:n))}
 async function saveSettings(next:ReminderSettings){setSettings(next);if(!userId)return;const s=createBrowserSupabase();const{error}=await s.from('notification_settings').upsert({user_id:userId,...next},{onConflict:'user_id'});setNoticeMsg(error?'Could not save reminder settings.':'Reminder settings saved.')}
 async function enableBrowserAlerts(){if(typeof window==='undefined'||!('Notification'in window)){setNoticeMsg('Browser notifications are not supported on this device.');return}const permission=await Notification.requestPermission();setNoticeMsg(permission==='granted'?'Browser notifications enabled. HomeKeep will show alerts when the app is active.':'Notification permission was not enabled.')}
 function status(t:Task){const today=new Date().toISOString().slice(0,10);if(t.due_date<today)return['overdue','Overdue'];const d=Math.ceil((new Date(t.due_date).getTime()-Date.now())/86400000);if(d<=30)return['soon',d<=0?'Due today':`Due in ${d}d`];return['',`Due ${new Date(t.due_date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}`]}

 return <main className="shell">
  <header className="topbar"><div className="brandWrap"><div className="brandMark">⌂</div><div><div className="brand">HomeKeep</div><div className="muted" style={{fontSize:13}}>Your home at a glance</div></div></div><div className="topActions"><button className="notifyButton" onClick={()=>setShowNotices(x=>!x)} aria-label="Notifications">🔔{unread>0&&<span className="notifyCount">{unread}</span>}</button><span className="badge">{userId?'● Synced':'Demo mode'}</span></div></header>

  {showNotices&&<section className="card notificationPanel"><div className="sectionHead"><div><h2 className="sectionTitle">Reminders</h2><div className="muted">HomeKeep checks your schedule automatically every hour.</div></div><button className="btn btnGhost btnSmall" onClick={enableBrowserAlerts}>Enable device alerts</button></div>{noticeMsg&&<div className="message">{noticeMsg}</div>}<div className="reminderSettings"><label className="field">Remind me before due<select className="input" value={settings.days_before} onChange={e=>saveSettings({...settings,days_before:Number(e.target.value)})}><option value={0}>Due date only</option><option value={1}>1 day before</option><option value={3}>3 days before</option><option value={7}>7 days before</option><option value={14}>14 days before</option></select></label><label className="toggleRow"><input type="checkbox" checked={settings.enabled} onChange={e=>saveSettings({...settings,enabled:e.target.checked})}/><span>Automatic reminders</span></label><label className="toggleRow"><input type="checkbox" checked={settings.remind_overdue} onChange={e=>saveSettings({...settings,remind_overdue:e.target.checked})}/><span>Overdue follow-ups</span></label></div><div className="notificationList">{notices.length===0?<div className="empty">No reminders yet. HomeKeep will add them when tasks approach their due dates.</div>:notices.map(n=><button key={n.id} className={`notificationItem ${n.read_at?'':'unread'}`} onClick={()=>markRead(n.id)}><span className="notificationDot">{n.kind==='overdue'?'!':'•'}</span><span><strong>{n.title}</strong><span>{n.body}</span></span>{!n.read_at&&<em>New</em>}</button>)}</div></section>}

  <section className="dashboardHero"><div className="card scoreCard"><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:13,opacity:.8,fontWeight:700}}>HOME HEALTH</div><h1 style={{fontSize:34,margin:'8px 0',letterSpacing:'-1px'}}>You’re keeping your home on track.</h1><div style={{opacity:.8,maxWidth:540,lineHeight:1.5}}>{counts.overdue?`You have ${counts.overdue} overdue ${counts.overdue===1?'task':'tasks'} to knock out.`:'No overdue maintenance right now. Nice work.'}</div><Link href="/setup" className="btn btnGhost" style={{display:'inline-block',marginTop:16}}>Personalize my home →</Link></div><div className="scoreRing" style={{'--score':`${score}%`} as React.CSSProperties}><div className="scoreValue">{score}</div></div></div></div><div className="card"><div className="sectionTitle">This month</div><p className="muted" style={{marginTop:4}}>A quick look at what needs attention.</p><div className="quickGrid"><div className="quickItem"><div className="stat">{counts.overdue}</div><div className="quickLabel">Overdue</div></div><div className="quickItem"><div className="stat">{counts.soon}</div><div className="quickLabel">Due soon</div></div><div className="quickItem"><div className="stat">{counts.done}</div><div className="quickLabel">Completed</div></div><div className="quickItem"><div className="stat">{tasks.length}</div><div className="quickLabel">Tracked</div></div></div></div></section>

  <section id="add" className="card"><div className="sectionHead"><div><h2 className="sectionTitle">Add a maintenance reminder</h2><div className="muted">Tell HomeKeep what to remember.</div></div><span className="badge">+ New task</span></div><form onSubmit={add} className="formGrid"><label className="field">Task<input className="input" value={name} onChange={e=>setName(e.target.value)} required placeholder="Replace HVAC filter"/></label><label className="field">Category<select className="input" value={category} onChange={e=>setCategory(e.target.value)}>{Object.keys(icons).map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Next due<input className="input" type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><label className="field">Repeat<select className="input" value={repeat} onChange={e=>setRepeat(Number(e.target.value))}><option value={30}>Monthly</option><option value={90}>Every 3 months</option><option value={180}>Every 6 months</option><option value={365}>Yearly</option></select></label><button className="btn btnPrimary">Save reminder</button></form>{msg&&<div className="message">{msg}</div>}</section>

  <section id="schedule" className="card" style={{marginTop:16}}><div className="sectionHead"><div><h2 className="sectionTitle">Maintenance schedule</h2><div className="muted">Your next home-care jobs, in order.</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btnGhost btnSmall" onClick={()=>setShowHistory(x=>!x)}>{showHistory?'Hide history':'View history'}</button><span className="badge">{tasks.length} tracked</span></div></div><div className="taskList">{tasks.length===0?<div className="empty">No maintenance reminders yet.</div>:tasks.slice().sort((a,b)=>a.due_date.localeCompare(b.due_date)).map(t=>{const[cls,label]=status(t);return <div className="task" key={t.id}><div className="taskMain"><div className="taskIcon">{icons[t.category]||'🔧'}</div><div><div className="taskName">{t.name}</div><div className="taskMeta">{t.category} · repeats every {t.repeat_days} days{t.last_completed_at?` · last done ${new Date(t.last_completed_at).toLocaleDateString()}`:''}</div><div style={{marginTop:8}}><span className={`statusPill ${cls}`}>{label}</span></div></div></div><button className="btn btnGhost btnSmall" onClick={()=>complete(t)}>✓ Mark done</button></div>})}</div></section>

  {showHistory&&<section className="card" style={{marginTop:16}}><div className="sectionHead"><div><h2 className="sectionTitle">Maintenance history</h2><div className="muted">A record of work completed on your home.</div></div><span className="badge">{history.length} records</span></div><div className="taskList">{history.length===0?<div className="empty">Nothing completed yet.</div>:history.slice(0,20).map(h=>{const t=taskById.get(h.task_id);return <div className="task" key={h.id}><div className="taskMain"><div className="taskIcon">✓</div><div><div className="taskName">{t?.name||'Maintenance task'}</div><div className="taskMeta">{t?.category||'Home maintenance'} · completed {new Date(h.completed_at).toLocaleDateString()}</div></div></div></div>})}</div></section>}

  <nav className="bottomNav"><Link className="active" href="/dashboard"><span className="navIcon">⌂</span><span>Home</span></Link><a href="#add"><span className="navIcon">＋</span><span>Add</span></a><a href="#schedule"><span className="navIcon">☷</span><span>Schedule</span></a></nav>
 </main>
}
